"""added new devs,freebies and companies

Revision ID: 357f97d63ff3
Revises: 31cf01ac1e0b
Create Date: 2025-05-24 12:55:26.092902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '357f97d63ff3'
down_revision: Union[str, None] = '31cf01ac1e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
