"""established relationships and aggregate methods

Revision ID: 7170b02ba09e
Revises: 625f9bd0336c
Create Date: 2025-05-25 16:52:02.055558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7170b02ba09e'
down_revision: Union[str, None] = '625f9bd0336c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
