"""added more devs,freebies and companies version test

Revision ID: 80322e45fdb8
Revises: 357f97d63ff3
Create Date: 2025-05-24 12:59:23.106017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80322e45fdb8'
down_revision: Union[str, None] = '357f97d63ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
